version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: innovatech_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - back-net

  backend:
    build: ./backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: innovatech_db
      DB_USER: root
    depends_on:
      - db
    networks:
      - back-net
      - front-net

  frontend:
    build: ./frontend
    ports:
      - "80:5000"
    environment:
      BACKEND_URL: http://backend:8000
    networks:
      - front-net

volumes:
  db_data:

networks:
  front-net:
  back-net:
    internal: true