name: Deploy Innovatech Stack

on:
  push:
    branches: [ deploy ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      
      - name: Build and Push
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/front-innovatech:latest ./frontend
          docker push ${{ secrets.DOCKER_USER }}/front-innovatech:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            docker-compose pull
            docker-compose up -d